### ISSUE TITLE
Exception when indexing (I think)

### ISSUE THREAD

**Issue by jbouzekri** [pascalw/jekyll_indextank#3]
Hi,

I do not know ruby so my explanation could be shaky. I installed your plugin, built it with rake and added it to my _plugin folder.

When I launch a jekyll build command, I have the following exception :
```
jobou@maison-linux:~/workspace/site-perso/blog$ jekyll build --trace
Configuration file: /home/jobou/workspace/site-perso/blog/_config.yml
            Source: /home/jobou/workspace/site-perso/blog
       Destination: /home/jobou/workspace/site-perso/blog/_site
      Generating... 
Indexing pages...
/var/lib/gems/1.9.1/gems/indextank-1.0.13/lib/indextank/index.rb:71:in `running?': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/jobou/workspace/site-perso/blog/_plugins/jekyll_indextank.rb:46:in `generate'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/site.rb:227:in `block in generate'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/site.rb:226:in `each'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/site.rb:226:in `generate'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/site.rb:42:in `process'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/command.rb:43:in `process_site'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/commands/build.rb:46:in `build'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/commands/build.rb:30:in `process'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
	from /var/lib/gems/1.9.1/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/1.9.1/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/1.9.1/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/1.9.1/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/1.9.1/gems/mercenary-0.3.3/lib/mercenary/program.rb:35:in `go'
	from /var/lib/gems/1.9.1/gems/mercenary-0.3.3/lib/mercenary.rb:22:in `program'
	from /var/lib/gems/1.9.1/gems/jekyll-2.0.3/bin/jekyll:18:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
Any help ?
Thanks in advance

**Comment by pascalw** [comment]
Closing due to inactivity. Feel free to reopen if this is still an issue.
